name: Test

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Test Go-lang
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup golang environment
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'

      - name: Build tffreeze
        run: go test cmd/*.go
        shell: bash
